server.port=8082

spring.datasource.url=jdbc:h2:mem:ticket-booking;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=very-secret-key-change-me-please-use-a-longer-secret-12345
jwt.expiration=86400000

booking.expiration.check-rate-ms=60000

auth.service.base-url=http://localhost:8081
auth.service.connect-timeout-ms=2000
auth.service.read-timeout-ms=5000

logging.level.org.springframework=INFO
logging.level.org.website=DEBUG
