package org.website.controller;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.website.dto.PaymentOrderRequest;
import org.website.dto.PaymentOrderResponse;
import org.website.dto.PaymentVerifyRequest;
import org.website.dto.RefundRequest;
import org.website.service.PaymentService;

/**
 * Payment Controller - Handles payment processing operations via Razorpay.
 * 
 * This controller manages the two-step payment flow:
 * 1. CREATE ORDER - Frontend requests order creation, backend calls Razorpay
 * 2. VERIFY PAYMENT - Frontend sends payment details, backend verifies signature
 * 
 * Endpoints:
 * - POST /api/payments/create-order - Initiate payment order
 * - POST /api/payments/verify - Verify payment signature and complete booking
 * 
 * Security: ALL endpoints require authentication (JWT token).
 * Payment verification uses HMAC-SHA256 signature validation for security.
 * 
 * Razorpay Integration:
 * - Order IDs are generated by Razorpay API
 * - Payment signatures are verified using secret key in application.properties
 * - On successful verification, booking status transitions to BOOKED
 * 
 * @author BookMyShow Dev Team
 * @version 1.0
 * @since 2026-05-30
 */
@RestController
@RequestMapping("/api/payments")
@Slf4j
public class PaymentController {

    private PaymentService paymentService;

    PaymentController(PaymentService paymentService) {
        this.paymentService = paymentService;
    }

    /**
     * Create a payment order on Razorpay.
     * 
     * Initiates a payment order by calling Razorpay API. The order ID is then
     * used by the frontend to open the Razorpay checkout modal where user
     * enters payment details (card, UPI, etc.).
     * 
     * Flow:
     * 1. Frontend calls this endpoint after selecting seats and confirming booking
     * 2. Backend retrieves booking details and calculates total amount
     * 3. Backend calls Razorpay API to create order
     * 4. Frontend receives order ID and opens Razorpay checkout modal
     * 5. User completes payment in modal
     * 6. Frontend calls /verify endpoint after payment (on success/failure)
     * 
     * @param userId Extracted from JWT token
     * @param request PaymentOrderRequest containing:
     *                - bookingId (required, booking must be in RESERVED status)
     * 
     * @return ResponseEntity containing PaymentOrderResponse with:
     *         - orderId (from Razorpay)
     *         - amount (in paise)
     *         - currency (always "INR")
     * @return HTTP 200 OK with payment order details
     * @return HTTP 400 BAD_REQUEST if booking not found or invalid (error_code: ERR106)
     * @return HTTP 403 FORBIDDEN if booking belongs to different user (error_code: ERR002)
     * @return HTTP 500 BAD_GATEWAY if Razorpay API error (error_code: ERR504)
     * 
     * @throws ResourceNotFoundException if booking not found
     * @throws UnauthorizedException if user doesn't own the booking
     * @throws InvalidPaymentException if Razorpay API error
     * 
     * Example Request:
     * {
     *   "bookingId": 101
     * }
     * 
     * Example Response (200):
     * {
     *   "orderId": "order_MBD7ukQ69xz6qJ",
     *   "amount": 75000,
     *   "currency": "INR"
     * }
     * 
     * FRONTEND NEXT STEPS:
     * 1. Use orderId to open Razorpay checkout
     * 2. User completes payment in modal
     * 3. On success, frontend receives:
     *    - razorpay_order_id
     *    - razorpay_payment_id
     *    - razorpay_signature
     * 4. Frontend calls /api/payments/verify with these details
     */
    @PostMapping("/create-order")
    public ResponseEntity<PaymentOrderResponse> createPaymentOrder(
            @RequestAttribute("userId") Long userId,
            @RequestBody PaymentOrderRequest request) {
        log.info("Creating payment order for booking reference: {} by user: {}", request.getBookingReference(), userId);
        PaymentOrderResponse response = paymentService.createPaymentOrder(userId, request);
        log.info("Payment order created with Razorpay order ID: {}", response.getOrderId());
        return ResponseEntity.ok(response);
    }

    /**
     * Verify Razorpay payment signature and complete booking.
     * 
     * Verifies the payment using HMAC-SHA256 signature validation. This ensures
     * that the payment details received from frontend are authentic and haven't
     * been tampered with.
     * 
     * Security:
     * - Uses Razorpay Secret Key stored in application.properties
     * - Calculates HMAC-SHA256 hash of "{orderId}|{paymentId}"
     * - Compares calculated hash with signature received from frontend
     * - Only proceeds if signatures match
     * 
     * Flow:
     * 1. Frontend sends payment details received from Razorpay modal
     * 2. Backend verifies signature using secret key
     * 3. If verified:
     *    - Booking status changes from RESERVED to BOOKED
     *    - Seats locked permanently
     *    - Payment status set to COMPLETED
     *    - Notification email sent with ticket details
     * 4. If not verified:
     *    - Payment status set to FAILED
     *    - Booking returned to available for new attempt
     *    - Seats released back to AVAILABLE
     * 
     * @param userId Extracted from JWT token
     * @param request PaymentVerifyRequest containing:
     *                - bookingId (required)
     *                - razorpayOrderId (required, from Razorpay modal)
     *                - razorpayPaymentId (required, from Razorpay modal)
     *                - razorpaySignature (required, HMAC-SHA256 signature)
     * 
     * @return ResponseEntity containing success message
     * @return HTTP 200 OK on successful verification
     * @return HTTP 400 BAD_REQUEST if signature invalid (error_code: ERR301)
     * @return HTTP 403 FORBIDDEN if booking belongs to different user (error_code: ERR002)
     * @return HTTP 404 NOT_FOUND if booking not found (error_code: ERR106)
     * 
     * @throws InvalidPaymentException if signature verification fails
     * @throws ResourceNotFoundException if booking not found
     * @throws UnauthorizedException if user doesn't own the booking
     * 
     * Example Request:
     * {
     *   "bookingId": 101,
     *   "razorpayOrderId": "order_MBD7ukQ69xz6qJ",
     *   "razorpayPaymentId": "pay_MBD7vg4jKJFtQe",
     *   "razorpaySignature": "9ef4dffbfd84f1318f6739a3ce19f9d85851857ae648f114332d8401e0949a3d"
     * }
     * 
     * Example Response (200):
     * {
     *   "message": "Payment verified successfully"
     * }
     * 
     * Error Response (400 - Signature Mismatch):
     * {
     *   "error_code": "ERR301",
     *   "message": "Payment signature verification failed",
     *   "status": 400,
     *   "error_type": "PAYMENT_INVALID_SIGNATURE",
     *   "timestamp": "2026-05-30T10:35:00"
     * }
     * 
     * FRONTEND NEXT STEPS (on success):
     * 1. Redirect user to "Ticket Confirmed" page
     * 2. Display booking reference and ticket details
     * 3. Optionally email ticket (backend also sends email)
     * 4. Allow user to download ticket PDF
     */
    @PostMapping("/verify")
    public ResponseEntity<String> verifyPayment(
            @RequestAttribute("userId") Long userId,
            @RequestBody PaymentVerifyRequest request) {
        log.info("Verifying payment for order: {} by user: {}", request.getRazorpayOrderId(), userId);
        boolean verified = paymentService.verifyPayment(userId, request);
        
        if (verified) {
            log.info("Payment verified successfully for order: {}", request.getRazorpayOrderId());
            return ResponseEntity.ok("Payment verified successfully");
        } else {
            log.error("Payment verification failed for order: {}", request.getRazorpayOrderId());
            return ResponseEntity.badRequest().body("Payment verification failed");
        }
    }

    @PostMapping("/refund")
    public ResponseEntity<String> refundBooking(
            @RequestAttribute("userId") Long userId,
            @RequestBody RefundRequest request) {
        log.info("Processing refund for booking reference: {} by user: {}", request.getBookingReference(), userId);
        boolean refunded = paymentService.refundBooking(userId, request.getBookingReference());

        if (refunded) {
            log.info("Refund successfully initiated for booking reference: {}", request.getBookingReference());
            return ResponseEntity.ok("Refund initiated successfully");
        }

        log.error("Refund initiation failed for booking reference: {}", request.getBookingReference());
        return ResponseEntity.status(500).body("Refund could not be processed");
    }
}
