CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    profile_picture_url VARCHAR(500),
    role VARCHAR(50) NOT NULL
);

CREATE TABLE theaters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    screens INTEGER NOT NULL
);

CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    genre VARCHAR(100) NOT NULL,
    duration INTEGER NOT NULL,
    language VARCHAR(100) NOT NULL,
    poster_url VARCHAR(500) NOT NULL,
    release_date VARCHAR(50) NOT NULL,
    rating DOUBLE PRECISION NOT NULL
);

CREATE TABLE shows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL,
    theater_id BIGINT NOT NULL,
    show_time TIMESTAMP NOT NULL,
    total_seats INTEGER NOT NULL,
    price_in_cents BIGINT NOT NULL,
    screen INTEGER NOT NULL,
    CONSTRAINT fk_show_movie FOREIGN KEY (movie_id) REFERENCES movies(id),
    CONSTRAINT fk_show_theater FOREIGN KEY (theater_id) REFERENCES theaters(id)
);

CREATE TABLE seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id BIGINT NOT NULL,
    seat_number INTEGER NOT NULL,
    seat_row INTEGER NOT NULL,
    seat_column INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,
    version BIGINT,
    CONSTRAINT fk_seat_show FOREIGN KEY (show_id) REFERENCES shows(id),
    CONSTRAINT uq_show_seat UNIQUE (show_id, seat_number)
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    show_id BIGINT NOT NULL,
    booking_reference VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL,
    total_amount_in_cents BIGINT NOT NULL,
    booking_time TIMESTAMP NOT NULL,
    payment_time TIMESTAMP,
    payment_order_id VARCHAR(255),
    qr_code VARCHAR(500),
    CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_booking_show FOREIGN KEY (show_id) REFERENCES shows(id)
);

CREATE TABLE booking_seats (
    booking_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,
    CONSTRAINT pk_booking_seats PRIMARY KEY (booking_id, seat_id),
    CONSTRAINT fk_booking_seat_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
    CONSTRAINT fk_booking_seat_seat FOREIGN KEY (seat_id) REFERENCES seats(id)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    razorpay_order_id VARCHAR(255) NOT NULL UNIQUE,
    razorpay_payment_id VARCHAR(255) UNIQUE,
    razorpay_signature VARCHAR(500),
    status VARCHAR(50) NOT NULL,
    amount_in_cents BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES bookings(id)
);

CREATE INDEX idx_show_movie_id ON shows(movie_id);
CREATE INDEX idx_show_theater_id ON shows(theater_id);
CREATE INDEX idx_seat_show_id ON seats(show_id);
CREATE INDEX idx_booking_user_id ON bookings(user_id);
CREATE INDEX idx_booking_show_id ON bookings(show_id);
CREATE INDEX idx_payment_booking_id ON payments(booking_id);
