name: Maven Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build and Test
        working-directory: backend
        run: mvn clean verify

      - name: OWASP Dependency Check
        working-directory: backend
        run: mvn org.owasp:dependency-check-maven:check

      - name: Sonar Analysis
        working-directory: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar